# Generated by Django 4.2.7 on 2023-11-17 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=14, unique=True)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('client_short', models.CharField(max_length=10)),
                ('role_type', models.CharField(choices=[('ADMIN', 'Admin'), ('CLIENT', 'Client')], default='CLIENT', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('logos', models.ImageField(default='None', upload_to='client_logos/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('plan_type', models.CharField(max_length=20, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VDbApi',
            fields=[
                ('site_name', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('wind_speed_10m_mps', models.FloatField(blank=True, null=True)),
                ('wind_direction_in_deg', models.FloatField(blank=True, null=True)),
                ('temp_c', models.FloatField(blank=True, null=True)),
                ('nowcast_ghi_wpm2', models.FloatField(blank=True, null=True)),
                ('swdown2', models.FloatField(blank=True, null=True)),
                ('cs_data', models.FloatField(blank=True, null=True)),
                ('ci_data', models.FloatField(blank=True, null=True)),
                ('tz', models.TextField(blank=True, null=True)),
                ('ct_data', models.FloatField(blank=True, null=True)),
                ('ct_flag_data', models.TextField(blank=True, null=True)),
                ('forecast_method', models.TextField(blank=True, null=True)),
                ('log_ts', models.TextField(primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'db_table': 'v_db_api',
                'unique_together': {('timestamp', 'site_name')},
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=40)),
                ('capacity', models.FloatField(blank=True, null=True)),
                ('type', models.CharField(choices=[('Solar', 'Solar'), ('Wind', 'Wind')], default='Solar', max_length=12)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('log_ts', models.DateTimeField(auto_now_add=True)),
                ('site_status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='Active')),
                ('verified', models.CharField(choices=[('VERIFIED', 'Verified'), ('UNVERIFIED', 'Unverified')], default='UNVERIFIED')),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_name', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'site_config',
            },
        ),
        migrations.CreateModel(
            name='ClientPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.plans')),
            ],
        ),
    ]
