# Generated by Django 4.2.7 on 2023-11-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_usertokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='client_name',
            field=models.CharField(max_length=120),
        ),
    ]
